title: Thomas LaRock's Blog
description: Database and technology insights
baseurl: "/blog"
url: "https://sqlrockstar.github.io"
permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

markdown: kramdown
highlighter: rouge
theme: minima
