name: Debug WordPress Import

on:
  workflow_dispatch:
    inputs:
      xml_url:
        description: 'URL to WordPress XML file'
        required: true
        type: string

permissions:
  contents: write

jobs:
  debug:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Download and analyze XML file
      run: |
        echo "Downloading XML from: ${{ github.event.inputs.xml_url }}"
        curl -L -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36" -o wordpress-export.xml "${{ github.event.inputs.xml_url }}"
        
        echo "File downloaded. Size: $(wc -c < wordpress-export.xml) bytes"
        echo "First 20 lines of XML:"
        head -20 wordpress-export.xml
        echo ""
        echo "Checking for posts in XML:"
        grep -c "<item>" wordpress-export.xml || echo "No items found"
        grep -c "<wp:post_type>post</wp:post_type>" wordpress-export.xml || echo "No post types found"
        echo ""
        echo "Sample post titles:"
        grep -A 1 "<title>" wordpress-export.xml | head -10
        
    - name: Set up Ruby and Jekyll
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        
    - name: Install dependencies
      run: |
        gem install jekyll bundler
        gem install jekyll-import
        gem install hpricot
        gem install open_uri_redirections
        gem install nokogiri
        
    - name: Create blog directory
      run: |
        mkdir -p blog/_posts
        mkdir -p blog/assets/images
        
    - name: Test Jekyll import with verbose output
      run: |
        cd blog
        echo "Starting Jekyll import..."
        ruby -r rubygems -e "
        require 'jekyll-import'
        puts 'Jekyll import loaded successfully'
        
        # Enable verbose output
        puts 'Starting WordPress.com import...'
        
        JekyllImport::Importers::WordpressDotCom.run({
          'source' => '../wordpress-export.xml',
          'no_fetch_images' => false,
          'assets_folder' => 'assets'
        })
        
        puts 'Import completed'
        " || echo "Import failed"
        
    - name: Check results
      run: |
        cd blog
        echo "Files created in _posts directory:"
        ls -la _posts/ || echo "No _posts directory or files"
        echo ""
        echo "Total files in _posts:"
        find _posts -name "*.markdown" -o -name "*.md" | wc -l || echo "0"
        echo ""
        echo "Sample post files:"
        find _posts -name "*.markdown" -o -name "*.md" | head -5
        echo ""
        echo "First few lines of a sample post:"
        find _posts -name "*.markdown" -o -name "*.md" | head -1 | xargs head -10 || echo "No posts to show"
